version: '3'
services:
  grpc-crashing-server:
    build:
      context: ./java
      dockerfile: Dockerfile
    command: sh -c "java -cp /app/target/java-1.0-SNAPSHOT.jar org.demo.server.GrpcCrashingServer"
    environment:
      - JWT_SECRET=L8hHXsaQOUjk5rg7XPGv4eL36anlCrkMz8CJ0i/8E/0=
    volumes:
      - ./java/target:/app/target
      - ./tls_credentials:/app/tls_credentials
      - ./retrying_config.json:/app/retrying_config.json

  grpc-java-client:
    build:
      context: ./java
      dockerfile: Dockerfile
    command: sh -c "java -cp /app/target/java-1.0-SNAPSHOT.jar org.demo.client.GrpcResilientClient"
    environment:
      - JWT_SECRET=L8hHXsaQOUjk5rg7XPGv4eL36anlCrkMz8CJ0i/8E/0=
    volumes:
      - ./java/target:/app/target
      - ./tls_credentials:/app/tls_credentials
      - ./retrying_config.json:/app/retrying_config.json

  grpc-kotlin-client:
    build:
      context: ./kotlin
      dockerfile: Dockerfile
    command: sh -c "java -cp /app/target/kotlin-1.0-SNAPSHOT.jar org.demo.client.GrpcResilientClient"
    environment:
      - JWT_SECRET=L8hHXsaQOUjk5rg7XPGv4eL36anlCrkMz8CJ0i/8E/0=
    volumes:
      - ./kotlin/target:/app/target
      - ./tls_credentials:/app/tls_credentials
      - ./retrying_config.json:/app/retrying_config.json

  grpc-python-client:
    build:
      context: ./python
      dockerfile: Dockerfile
    command: >
      sh -c "
      python -m venv venv &&
      . venv/bin/activate &&
      pip install --no-cache-dir -r requirements.txt &&
      python -c \"from grpc_tools import protoc; protoc.main(['', '--python_out=.', '--grpc_python_out=.', '--proto_path=proto', 'social-media-stream.proto'])\" &&
      python -m src.client.grpc_resilient_client"
    environment:
      - JWT_SECRET=L8hHXsaQOUjk5rg7XPGv4eL36anlCrkMz8CJ0i/8E/0=
    volumes:
      - ./python:/app
      - ./proto:/app/proto
      - ./tls_credentials:/app/tls_credentials
      - ./retrying_config.json:/app/retrying_config.json
