apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  restartPolicy: Never
  containers:
    - name: server
      image: grpc-python-server:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9030
      env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET