apiVersion: v1
kind: Pod
metadata:
  name: python-server
  labels:
    app: python-server
spec:
  restartPolicy: Never
  containers:
    - name: python-server
      image: grpc-python-server:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9030
      env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: SERVER_HOST
          value: grpc-crashing-server
        - name: SERVER_PORT
          value: "80"