FROM python:3.8-slim-buster

WORKDIR /app

COPY python /app
COPY proto /app/proto
COPY tls_credentials /app/tls_credentials
COPY retrying_config.json /app/retrying_config.json

ENV JWT_SECRET="L8hHXsaQOUjk5rg7XPGv4eL36anlCrkMz8CJ0i/8E/0="

CMD ["sh", "-c", "python -m venv venv && . venv/bin/activate && ls && pip install --no-cache-dir -r requirements.txt && python -c \"from grpc_tools import protoc; protoc.main(['', '--python_out=.', '--grpc_python_out=.', '--proto_path=proto', 'social-media-stream.proto'])\" && python -m src.client.grpc_resilient_client"]
