apiVersion: v1
kind: Pod
metadata:
  name: kotlin-client
  labels:
    app: kotlin-client
spec:
  restartPolicy: Never
  containers:
    - name: grpc-kotlin-client
      image: grpc-kotlin-client:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9030
      env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: SERVER_HOST
          value: grpc-crashing-server
        - name: SERVER_PORT
          value: "80"